// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheLsmArchive.Database.DbContext;

#nullable disable

namespace TheLsmArchive.Database.Migrations
{
    [DbContext(typeof(LsmArchiveDbContext))]
    [Migration("20260308204918_AddTopicNormalizedNameKey")]
    partial class AddTopicNormalizedNameKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheLsmArchive.Database.Entities.EpisodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PatreonPostId")
                        .HasColumnType("integer")
                        .HasColumnName("patreon_post_id");

                    b.Property<DateTimeOffset>("ReleaseDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date_utc");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer")
                        .HasColumnName("show_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("PatreonPostId")
                        .IsUnique()
                        .HasDatabaseName("ix_episodes_patreon_post_id");

                    b.HasIndex("ShowId")
                        .HasDatabaseName("ix_episodes_show_id");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PatreonPostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("audio_url");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("link");

                    b.Property<int>("PatreonId")
                        .HasColumnType("integer")
                        .HasColumnName("patreon_id");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("processing_error");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer")
                        .HasColumnName("show_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_patreon_posts");

                    b.HasIndex("ShowId", "PatreonId")
                        .IsUnique()
                        .HasDatabaseName("ix_patreon_posts_show_id_patreon_id");

                    b.ToTable("patreon_posts", (string)null);
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_name");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PersonEpisodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_person_episodes");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_person_episodes_episode_id");

                    b.HasIndex("PersonId", "EpisodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_episodes_person_id_episode_id");

                    b.ToTable("person_episodes", (string)null);
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PersonTopicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_person_topics");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_person_topics_topic_id");

                    b.HasIndex("PersonId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_topics_person_id_topic_id");

                    b.ToTable("person_topics", (string)null);
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.ShowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_shows");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_shows_name");

                    b.ToTable("shows", (string)null);
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.TopicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_topics_name");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_topics_normalized_name");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.TopicEpisodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_topic_episodes");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_topic_episodes_episode_id");

                    b.HasIndex("TopicId", "EpisodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_topic_episodes_topic_id_episode_id");

                    b.ToTable("topic_episodes", (string)null);
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.EpisodeEntity", b =>
                {
                    b.HasOne("TheLsmArchive.Database.Entities.PatreonPostEntity", "PatreonPost")
                        .WithOne("Episode")
                        .HasForeignKey("TheLsmArchive.Database.Entities.EpisodeEntity", "PatreonPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_patreon_posts_patreon_post_id");

                    b.HasOne("TheLsmArchive.Database.Entities.ShowEntity", "Show")
                        .WithMany("Episodes")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_shows_show_id");

                    b.Navigation("PatreonPost");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PatreonPostEntity", b =>
                {
                    b.HasOne("TheLsmArchive.Database.Entities.ShowEntity", "Show")
                        .WithMany("PatreonPosts")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patreon_posts_shows_show_id");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PersonEpisodeEntity", b =>
                {
                    b.HasOne("TheLsmArchive.Database.Entities.EpisodeEntity", "Episode")
                        .WithMany("PersonEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_episodes_episodes_episode_id");

                    b.HasOne("TheLsmArchive.Database.Entities.PersonEntity", "Person")
                        .WithMany("PersonEpisodes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_episodes_persons_person_id");

                    b.Navigation("Episode");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PersonTopicEntity", b =>
                {
                    b.HasOne("TheLsmArchive.Database.Entities.PersonEntity", "Person")
                        .WithMany("PersonTopics")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_topics_persons_person_id");

                    b.HasOne("TheLsmArchive.Database.Entities.TopicEntity", "Topic")
                        .WithMany("PersonTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_topics_topics_topic_id");

                    b.Navigation("Person");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.TopicEpisodeEntity", b =>
                {
                    b.HasOne("TheLsmArchive.Database.Entities.EpisodeEntity", "Episode")
                        .WithMany("TopicEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_topic_episodes_episodes_episode_id");

                    b.HasOne("TheLsmArchive.Database.Entities.TopicEntity", "Topic")
                        .WithMany("TopicEpisodes")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_topic_episodes_topics_topic_id");

                    b.Navigation("Episode");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.EpisodeEntity", b =>
                {
                    b.Navigation("PersonEpisodes");

                    b.Navigation("TopicEpisodes");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PatreonPostEntity", b =>
                {
                    b.Navigation("Episode");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.PersonEntity", b =>
                {
                    b.Navigation("PersonEpisodes");

                    b.Navigation("PersonTopics");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.ShowEntity", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("PatreonPosts");
                });

            modelBuilder.Entity("TheLsmArchive.Database.Entities.TopicEntity", b =>
                {
                    b.Navigation("PersonTopics");

                    b.Navigation("TopicEpisodes");
                });
#pragma warning restore 612, 618
        }
    }
}
